server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
    alibaba:
      seata:
        tx-service-group: fsp_zrc_group
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver                #mysql驱动包
    url: jdbc:mysql://192.168.1.5:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml