server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route #payment_route  #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配的进行路由

        - id: payment_route2 #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001      #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         #断言，路径相匹配的进行路由
            - After=2020-04-26T16:30+08:00[Asia/Shanghai]

        - id: payment_route3 #payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: https://news.baidu.com/guonei      #匹配后提供服务的路由地址
          predicates:
              - Path=/guonei         #断言，路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
